# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_double <- function(vec, n_min_size) {
    .Call('_armbart_sample_double', PACKAGE = 'armbart', vec, n_min_size)
}

cpp_rgamma <- function(n, shape, scale) {
    .Call('_armbart_cpp_rgamma', PACKAGE = 'armbart', n, shape, scale)
}

dhcauchy <- function(x, location, sigma) {
    .Call('_armbart_dhcauchy', PACKAGE = 'armbart', x, location, sigma)
}

bart <- function(x_train, y, x_test, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta, a_tau, d_tau) {
    .Call('_armbart_bart', PACKAGE = 'armbart', x_train, y, x_test, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta, a_tau, d_tau)
}

